<?php
/**
 * Genesis Framework.
 *
 * WARNING: This file is part of the core Genesis Framework. DO NOT edit this file under any circumstances.
 * Please do all modifications in the form of a child theme.
 *
 * @package Genesis\Templates
 * @author  StudioPress
 * @license GPL-2.0-or-later
 * @link    https://my.studiopress.com/themes/genesis/
 */

/**
 * Fires at start of header.php, immediately before `genesis_title` action hook to render the Doctype content.
 *
 * @since 1.3.0
 */
do_action( 'genesis_doctype' );

/**
 * Fires immediately after `genesis_doctype` action hook, in header.php to render the document title.
 *
 * @since 1.0.0
 */
do_action( 'genesis_title' );

/**
 * Fires immediately after `genesis_title` action hook, in header.php to render the meta elements.
 *
 * @since 1.0.0
 */
do_action( 'genesis_meta' );

wp_head(); // We need this for plugins.
?>
<style id="fcp-critical-css">
/* header */

/* / header */
</style>
</head>
<?php
genesis_markup(
	[
		'open'    => '<body %s>',
		'context' => 'body',
	]
);

if ( function_exists( 'wp_body_open' ) ) {
	wp_body_open();
}

/**
 * Fires immediately after the `wp_body_open` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before' );

genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-container',
	]
);

/**
 * Fires immediately after the site container opening markup, before `genesis_header` action hook.
 *
 * @since 1.0.0
 */
do_action( 'genesis_before_header' );

/**
 * Fires to display the main header content.
 *
 * @since 1.0.2
 */
//do_action( 'genesis_header' );

/**
 * Fires immediately after the `genesis_header` action hook, before the site inner opening markup.
 *
 * @since 1.0.0
 */
do_action( 'genesis_after_header' );
?>
<header class="site-header">
	<div class="container desktop-menu-container">
		<div class="tb-topbar">
			<?php
 				if ( is_active_sidebar( 'topbar-social-media' ) ) : ?>
	 				<div id="topbar-social-media" class="topbar-social-media" role="complementary">
	 					<?php dynamic_sidebar( 'topbar-social-media' ); ?>
	 				</div>
 			<?php endif; ?>
			<div class="topbar-menu-right">
				<?php wp_nav_menu( array( 'theme_location' => 'topbar-menu' ) ); ?>	
			</div>
		</div>
		<div class="main-header">
			<!--Toggle Start -->
			<div id="togglerBtn" class="hamburger toggler-open">
				<div class="top-line"></div>
				<div class="mid-line"></div>
				<div class="bot-line"></div>
			</div><!-- Toggler End-->
			<div class="site-logo">
				<?php
					// Display the Custom Logo
					the_custom_logo();

					// No Custom Logo, just display the site's name
					if (!has_custom_logo()) {
    			?>
    			<h1><?php bloginfo('name'); ?></h1>
    			<?php } ?>
			</div>
			<div class="main-header-menu-right align-items-center position-relative">
				<?php wp_nav_menu(array( 'theme_location' => 'primary' )); ?>
				<div class="search-toogle">
					<a href="javascript:void(0);" class="fa fa-search"></a>
				</div>
				<div class="search-form"><?php echo do_shortcode('[wpdreams_ajaxsearchlite]'); ?></div>
			</div>
		</div>
	</div>

	<!-- mobile menu -->
	<div class="mobile-menu-container">
		<div class="mobile-menu-container-expandable">
			<?php wp_nav_menu(array( 'theme_location' => 'mobile-menu' )); ?>
				<form role="search" method="get" id="searchform" class="wp-searchform" action="<?php echo esc_url( home_url( '/' ) ); ?>">
					<div class="wp-searchform-container">
						<label class="screen-reader-text" for="s"><?php _x( 'Search for:', 'label' ); ?></label>
						<input type="text" value="<?php echo get_search_query(); ?>" name="s" id="s" />
						<button type="submit" id="searchsubmit"><span class="icon"><i class="fa fa-search"></i></span></button>
					</div>
				</form>
		</div>
	</div>
</header>
<?php
/* genesis_markup(
	[
		'open'    => '<div %s>',
		'context' => 'site-inner',
	]
);
genesis_structural_wrap( 'site-inner' ); */
